### ISSUE TITLE
Build tag graph

### ISSUE THREAD

**Issue by fouweric** [fouweric/wikileaks-data-analytics#18]
Input: plusD-database
Output: a file (matching specifications #11) where you put an edge of weight 1 between each pair of tag in each document tag­set

**Comment by xPh3n0m** [comment]
@fouweric I am trying to generate a graph using a modified version of GraphGenerator.scala for tags. However, for some reason I get an error when using spark-submit :

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.SQLContext.implicits()Lorg/apache/spark/sql/SQLContext$implicits$;
	at GraphGenerator$.main(GraphGenerator.scala:27)
	at GraphGenerator.main(GraphGenerator.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:358)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

Any idea of what it can be? I get the same thing when trying to construct the graph for emitter-receiver (your code).

Thanks

**Comment by fouweric** [comment]
We saw together and found that It was a spark configuration problem.

**Comment by xPh3n0m** [comment]
Added json files for tags in /website/graphs/tags_graphs

However, I have issues viewing the current index.html file, and thus to test my graphs. I get Uncaught ReferenceError: angular is not defined when opening the file from my localhost. Any ideas?

**Comment by xPh3n0m** [comment]
Ok it works with firefox. I added the tags graphs in index.html, but it doesn't seem to show anything relevant...
